/**
 * POST /api/mobile/invite/generate
 *
 * Idempotently creates or fetches the calling user's invite code.
 *
 * Behaviour:
 *   - If `users/{uid}/invite/code` already exists in Firestore → return it.
 *   - Otherwise generate a friendly code (e.g. "BUSHY-2K4J"), create a
 *     PromoCode doc with `inviterUserId = uid`, persist a pointer at
 *     `users/{uid}/invite/code`, and return the code.
 *
 * Body (optional):
 *   { firstName?: string }     // used as the code prefix, e.g. "BUSHY-…"
 *                              // if not provided, falls back to "PAW"
 *
 * Auth: Firebase ID token.
 *
 * Returns:
 *   200 { code: "BUSHY-2K4J", url: "https://pawpilot.xyz/r/BUSHY-2K4J",
 *         message: "Give 30 days of Pro, get 30 days of Pro." }
 */

import { NextRequest, NextResponse } from 'next/server';
import { randomBytes } from 'node:crypto';
import { requireMobileUser } from '@/lib/pawme-mobile';
import { adminDb } from '@/lib/firebase-admin';
import { runApi } from '@/lib/pawme-logging';
import { PromoCode } from '@/lib/promo-types';

const ENDPOINT = 'mobile/invite/generate';

const PUBLIC_SITE = process.env.NEXT_PUBLIC_APP_URL || 'https://pawpilot.xyz';

/** 30 days of Pro for both inviter + invitee — matches the Friends tier. */
const INVITE_DAYS = 30;
const ENTITLEMENT_ID = 'pro_access';

function makeCode(prefix: string): string {
  const clean = prefix.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 8);
  const tail = randomBytes(2).toString('hex').toUpperCase(); // 4 hex chars
  return `${clean || 'PAW'}-${tail}`;
}

export async function POST(request: NextRequest) {
  const { requestId, result, error } = await runApi(
    { endpoint: ENDPOINT, request },
    async ({ logInfo }) => {
      const { uid } = await requireMobileUser(request);
      const body = await request.json().catch(() => ({}));
      const firstName = String(body?.firstName || '').trim();

      logInfo({ uid, hasFirstName: Boolean(firstName) });

      const pointerRef = adminDb
        .collection('users')
        .doc(uid)
        .collection('invite')
        .doc('code');

      // Idempotent: return existing code if we've generated one already.
      const existing = await pointerRef.get();
      if (existing.exists) {
        const code = String(existing.data()?.code || '');
        if (code) {
          return {
            code,
            url: `${PUBLIC_SITE}/r/${code}`,
            message: `Give ${INVITE_DAYS} days of Pro, get ${INVITE_DAYS} days of Pro.`,
            existed: true,
          };
        }
      }

      // Generate a unique code — collisions rare for the 4-hex tail but possible.
      let code = '';
      for (let i = 0; i < 8; i++) {
        const candidate = makeCode(firstName || 'PAW');
        const snap = await adminDb.collection('promoCodes').doc(candidate).get();
        if (!snap.exists) {
          code = candidate;
          break;
        }
      }
      if (!code) {
        const err: Error & { statusCode?: number } = new Error(
          'Could not generate a unique invite code, please retry.',
        );
        err.statusCode = 500;
        throw err;
      }

      const now = new Date().toISOString();
      const farFuture = new Date(Date.now() + 365 * 5 * 24 * 60 * 60 * 1000).toISOString();

      const doc: PromoCode = {
        code,
        quantity: null, // unlimited — every friend redeems independently
        redeemedCount: 0,
        expiresAt: farFuture,
        status: 'active',
        discount: {
          type: 'trial_days',
          value: INVITE_DAYS,
          entitlementId: ENTITLEMENT_ID,
          productId: 'pawpilot_pro_monthly',
        },
        inviterUserId: uid,
        inviterReward: {
          type: 'trial_days',
          value: INVITE_DAYS,
          entitlementId: ENTITLEMENT_ID,
          productId: 'pawpilot_pro_monthly',
        },
        notes: `Invite code generated by ${uid}${firstName ? ` (${firstName})` : ''}`,
        createdBy: `invite:${uid}`,
        createdAt: now,
        updatedAt: now,
      };

      // Two writes inside a batch so we never end up with the pointer
      // pointing at a code that doesn't exist (or vice versa).
      const batch = adminDb.batch();
      batch.set(adminDb.collection('promoCodes').doc(code), doc);
      batch.set(pointerRef, { code, createdAt: now });
      await batch.commit();

      return {
        code,
        url: `${PUBLIC_SITE}/r/${code}`,
        message: `Give ${INVITE_DAYS} days of Pro, get ${INVITE_DAYS} days of Pro.`,
        existed: false,
      };
    },
  );

  if (error) {
    const status =
      typeof (error as any)?.statusCode === 'number' ? (error as any).statusCode : 500;
    return NextResponse.json(
      { error: (error as Error)?.message || 'error', requestId },
      { status, headers: { 'x-request-id': requestId } },
    );
  }
  return NextResponse.json(
    { ...(result as object), requestId },
    { headers: { 'x-request-id': requestId } },
  );
}
